### ISSUE TITLE
Hope to support sentence_transformers.CrossEncoder 

### ISSUE THREAD

**Issue by shell-nlp** [kevaldekivadiya2415/textembed#12]
Hope to support sentence_transformers.CrossEncoder

**Comment by kevaldekivadiya2415** [comment]
@shell-nlp looking for contributors.

**Comment by shell-nlp** [comment]
我的项目参考了你项目的实现方式，已经实现了CrossEncoder 
My project has taken a cue from your project's implementation and has implemented CrossEncoder

https://github.com/shell-nlp/gpt_server/blob/main/gpt_server/model_worker/embedding_v2.py

**Comment by rolandtannous** [comment]
@shell-nlp why not push a PR here too
